import type { CardData } from "./types";

/** Jeu de démo : une carte représentative par niveau (N1 → N4). */
export const DEMO_CARDS: CardData[] = [
  {
    id: "alex-recettes",
    level: 1,
    domain: "recettes-alex.fr",
    url: "recettes-alex.fr/galettes",
    anchor: "recette de galette",
    element: "sante",
    thematique: "CUISINE",
    summary: "Carnet de recettes du quotidien, lectorat famille.",
    hp: 26,
    atk: 12,
    tf: 14,
    cf: 19,
    dr: 18,
    linkType: "dofollow",
    owner: "Alex M.",
    status: "dispo",
    price: 1,
    edition: "241",
    editionTotal: "300",
  },
  {
    id: "alex-tech",
    level: 2,
    domain: "alex-tech.fr",
    url: "alex-tech.fr/outils-seo-2026",
    anchor: "meilleurs outils SEO",
    element: "tech",
    thematique: "TECH",
    summary: "Blog dev personnel, niche outils SEO et IA.",
    hp: 52,
    atk: 38,
    tf: 36,
    cf: 41,
    dr: 58,
    linkType: "dofollow",
    owner: "Alex M.",
    status: "dispo",
    price: 4,
    edition: "073",
    editionTotal: "300",
  },
  {
    id: "jdg",
    level: 3,
    domain: "journal-du-geek.fr",
    url: "journal-du-geek.fr/test-rtx",
    anchor: "comparatif cartes graphiques",
    element: "media",
    thematique: "PRESSE",
    summary: "Média tech national, actu hardware et culture geek.",
    hp: 72,
    atk: 66,
    tf: 64,
    cf: 60,
    dr: 74,
    linkType: "nofollow",
    owner: "Thomas R.",
    status: "dispo",
    price: 14,
    edition: "012",
    editionTotal: "300",
  },
  {
    id: "lemonde",
    level: 4,
    domain: "lemonde.fr",
    url: "lemonde.fr/economie/seo-ia",
    anchor: "référencement et IA générative",
    element: "media",
    thematique: "PRESSE",
    summary: "Quotidien de référence. Autorité éditoriale exceptionnelle.",
    hp: 95,
    atk: 92,
    tf: 92,
    cf: 88,
    dr: 96,
    linkType: "dofollow",
    owner: "Le Monde",
    status: "verrouillee",
    price: 47,
    edition: "001",
    editionTotal: "300",
  },
];
